name: build-docs
description: "Build cargo docs and upload as a GitHub Pages artifact."

inputs:
  target:
    description: Build target.
    required: true

runs:
  using: composite
  steps:
    - name: Doc
      run: cargo doc --target ${{ inputs.target }}
      shell: bash

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
      with:
        path: ./target/${{ inputs.target }}/doc
