[package]
name = "classicube-sys"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.5.1"

[build-dependencies]
bindgen = { version = "0.51.1", optional = true }
cc = "1.0.47"
fs_extra = "1.1.0"
