[package]
name = "classicube-sys"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
paste = "1.0.0"

[build-dependencies]
bindgen = "0.54.1"
cc = "1.0.58"
fs_extra = "1.1.0"
regex = "1.3.9"
