[package]
name = "classicube-sys"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
paste = "1.0.1"

[build-dependencies]
bindgen = "0.55.1"
cc = "1.0.60"
fs_extra = "1.2.0"
regex = "1.3.9"
