[package]
name = "classicube-sys"
version = "1.2.5"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
paste = "1"

[build-dependencies]
bindgen = "0.56"
cc = "1"
fs_extra = "1"
regex = "1"
