[package]
name = "classicube-sys"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
paste = "1.0"

[build-dependencies]
bindgen = "0.56"
cc = "1.0"
fs_extra = "1.2"
regex = "1.4"
