[package]
name = "classicube-sys"
version = "1.3.1"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2021"

[dependencies]
paste = "1"

[build-dependencies]
bindgen = "0.59"
cc = "1"
fs_extra = "1"
regex = "1"
