name: install-build-test
description: ""

inputs:
  target:
    description: Build target.
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      with:
        submodules: recursive

    - name: Install rust
      run: |
        rustup default stable
        rustup component add rustfmt
        rustup target add ${{ inputs.target }}
      shell: bash

    - name: Build
      run: |
        cargo build --target ${{ inputs.target }}
      shell: bash

    - name: Test
      run: |
        cargo test --target ${{ inputs.target }} -- --nocapture --test-threads 1
      shell: bash
