name: install-build-test
description: "Install rust, build, and test with nextest for the given target."

inputs:
  target:
    description: Build target.
    required: true

runs:
  using: composite
  steps:
    - name: Install rust
      run: |
        rustup default stable
        rustup component add rustfmt
        rustup target add ${{ inputs.target }}
      shell: bash

    - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      with:
        key: ${{ inputs.target }}
        save-if: ${{ !startsWith(github.ref, 'refs/tags/') }}

    - name: Build
      run: cargo build --target ${{ inputs.target }}
      shell: bash

    - uses: taiki-e/install-action@5bf6ce016fd2e72eefc647cbca1e4213f65955b8 # v2.87.5
      with:
        tool: cargo-nextest

    - name: Test
      run: cargo nextest run --target ${{ inputs.target }} --no-capture
      shell: bash
