name: install-build-test
description: "Install rust, build, and test with nextest for the given target."

inputs:
  target:
    description: Build target.
    required: true

runs:
  using: composite
  steps:
    - name: Install rust
      run: |
        rustup default stable
        rustup component add rustfmt
        rustup target add ${{ inputs.target }}
      shell: bash

    - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      with:
        key: ${{ inputs.target }}
        save-if: ${{ !startsWith(github.ref, 'refs/tags/') }}

    - name: Build
      run: cargo build --target ${{ inputs.target }}
      shell: bash

    - uses: taiki-e/install-action@c93ccc03e00cd0e08e494f5fd058a6c55a6a1907 # v2.82.8
      with:
        tool: cargo-nextest

    - name: Test
      run: cargo nextest run --target ${{ inputs.target }} --no-capture
      shell: bash
