use crate::bindings::*;

pub const Key_Function_Names: &[&str] = &[
    "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12", "F13", "F14", "F15",
    "F16", "F17", "F18", "F19", "F20", "F21", "F22", "F23", "F24",
];

pub const Key_Ascii_Names: &[&str] = &[
    "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S",
    "T", "U", "V", "W", "X", "Y", "Z",
];

pub const Pad_Names: &[&str] = &[
    "PAD_A",
    "PAD_B",
    "PAD_X",
    "PAD_Y",
    "PAD_L",
    "PAD_R",
    "PAD_LEFT",
    "PAD_RIGHT",
    "PAD_UP",
    "PAD_DOWN",
    "PAD_START",
    "PAD_SELECT",
    "PAD_ZL",
    "PAD_ZR",
];

pub const storageNames: [&str; InputButtons_INPUT_COUNT as usize] = [
    "None",
    // Key_Function_Names
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "F13",
    "F14",
    "F15",
    "F16",
    "F17",
    "F18",
    "F19",
    "F20",
    "F21",
    "F22",
    "F23",
    "F24",
    "Tilde",
    "Minus",
    "Plus",
    "BracketLeft",
    "BracketRight",
    "Slash",
    "Semicolon",
    "Quote",
    "Comma",
    "Period",
    "BackSlash",
    "ShiftLeft",
    "ShiftRight",
    "ControlLeft",
    "ControlRight",
    "AltLeft",
    "AltRight",
    "WinLeft",
    "WinRight",
    "Up",
    "Down",
    "Left",
    "Right",
    "Number0",
    "Number1",
    "Number2",
    "Number3",
    "Number4",
    "Number5",
    "Number6",
    "Number7",
    "Number8",
    "Number9",
    "Insert",
    "Delete",
    "Home",
    "End",
    "PageUp",
    "PageDown",
    "Menu",
    // Key_Ascii_Names
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "Enter",
    "Escape",
    "Space",
    "BackSpace",
    "Tab",
    "CapsLock",
    "ScrollLock",
    "PrintScreen",
    "Pause",
    "NumLock",
    "Keypad0",
    "Keypad1",
    "Keypad2",
    "Keypad3",
    "Keypad4",
    "Keypad5",
    "Keypad6",
    "Keypad7",
    "Keypad8",
    "Keypad9",
    "KeypadDivide",
    "KeypadMultiply",
    "KeypadSubtract",
    "KeypadAdd",
    "KeypadDecimal",
    "KeypadEnter",
    "XButton1",
    "XButton2",
    "LeftMouse",
    "RightMouse",
    "MiddleMouse",
    // Pad_Names
    "PAD_A",
    "PAD_B",
    "PAD_X",
    "PAD_Y",
    "PAD_L",
    "PAD_R",
    "PAD_LEFT",
    "PAD_RIGHT",
    "PAD_UP",
    "PAD_DOWN",
    "PAD_START",
    "PAD_SELECT",
    "PAD_ZL",
    "PAD_ZR",
];

pub const Input_DisplayNames: [&str; InputButtons_INPUT_COUNT as usize] = [
    "NONE",
    // Key_Function_Names
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "F13",
    "F14",
    "F15",
    "F16",
    "F17",
    "F18",
    "F19",
    "F20",
    "F21",
    "F22",
    "F23",
    "F24",
    "GRAVE",
    "MINUS",
    "PLUS",
    "LBRACKET",
    "RBRACKET",
    "SLASH",
    "SEMICOLON",
    "APOSTROPHE",
    "COMMA",
    "PERIOD",
    "BACKSLASH",
    "LSHIFT",
    "RSHIFT",
    "LCONTROL",
    "RCONTROL",
    "LALT",
    "RALT",
    "LWIN",
    "RWIN",
    "UP",
    "DOWN",
    "LEFT",
    "RIGHT",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "INSERT",
    "DELETE",
    "HOME",
    "END",
    "PRIOR",
    "DOWN",
    "MENU",
    // Key_Ascii_Names
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "RETURN",
    "ESCAPE",
    "SPACE",
    "BACK",
    "TAB",
    "CAPITAL",
    "SCROLL",
    "PRINT",
    "PAUSE",
    "NUMLOCK",
    "NUMPAD0",
    "NUMPAD1",
    "NUMPAD2",
    "NUMPAD3",
    "NUMPAD4",
    "NUMPAD5",
    "NUMPAD6",
    "NUMPAD7",
    "NUMPAD8",
    "NUMPAD9",
    "DIVIDE",
    "MULTIPLY",
    "SUBTRACT",
    "ADD",
    "DECIMAL",
    "NUMPADENTER",
    "XBUTTON1",
    "XBUTTON2",
    "LMOUSE",
    "RMOUSE",
    "MMOUSE",
    // Pad_Names
    "PAD_A",
    "PAD_B",
    "PAD_X",
    "PAD_Y",
    "PAD_L",
    "PAD_R",
    "PAD_LEFT",
    "PAD_RIGHT",
    "PAD_UP",
    "PAD_DOWN",
    "PAD_START",
    "PAD_SELECT",
    "PAD_ZL",
    "PAD_ZR",
];

pub const KeyBind_GamepadDefaults: [cc_uint8; KeyBind__KEYBIND_COUNT as usize] = [
    InputButtons_CCPAD_UP as _,
    InputButtons_CCPAD_DOWN as _,
    InputButtons_CCPAD_LEFT as _,
    InputButtons_CCPAD_RIGHT as _,
    InputButtons_CCPAD_A as _,
    0,
    InputButtons_CCPAD_START as _,
    InputButtons_CCPAD_Y as _,
    InputButtons_CCPAD_X as _,
    0,
    InputButtons_CCPAD_START as _,
    0,
    InputButtons_CCKEY_LSHIFT as _,
    b'X',
    b'Z',
    b'Q',
    b'E',
    0,
    0,
    0,
    0,
    InputButtons_CCKEY_F5 as _,
    0,
    0,
    0,
    0,
    InputButtons_CCPAD_L as _,
    0,
    InputButtons_CCPAD_R as _,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    InputButtons_CCPAD_ZL as _,
    InputButtons_CCPAD_ZR as _,
];

pub const KeyBind_NormalDefaults: [cc_uint8; KeyBind__KEYBIND_COUNT as usize] = [
    b'W',
    b'S',
    b'A',
    b'D',
    InputButtons_CCKEY_SPACE as _,
    b'R',
    InputButtons_CCKEY_ENTER as _,
    b'T',
    b'B',
    b'F',
    InputButtons_CCKEY_ENTER as _,
    InputButtons_CCKEY_TAB as _,
    InputButtons_CCKEY_LSHIFT as _,
    b'X',
    b'Z',
    b'Q',
    b'E',
    InputButtons_CCKEY_LALT as _,
    InputButtons_CCKEY_F3 as _,
    InputButtons_CCKEY_F12 as _,
    InputButtons_CCKEY_F11 as _,
    InputButtons_CCKEY_F5 as _,
    InputButtons_CCKEY_F1 as _,
    InputButtons_CCKEY_F7 as _,
    b'C',
    InputButtons_CCKEY_LCTRL as _,
    InputButtons_CCMOUSE_L as _,
    InputButtons_CCMOUSE_M as _,
    InputButtons_CCMOUSE_R as _,
    InputButtons_CCKEY_F6 as _,
    InputButtons_CCKEY_LALT as _,
    InputButtons_CCKEY_F8 as _,
    b'G',
    InputButtons_CCKEY_F10 as _,
    0,
    0,
    0,
    0,
    0,
    b'1',
    b'2',
    b'3',
    b'4',
    b'5',
    b'6',
    b'7',
    b'8',
    b'9',
    0,
    0,
];

pub const keybindNames: [&str; KeyBind__KEYBIND_COUNT as usize] = [
    "Forward",
    "Back",
    "Left",
    "Right",
    "Jump",
    "Respawn",
    "SetSpawn",
    "Chat",
    "Inventory",
    "ToggleFog",
    "SendChat",
    "PlayerList",
    "Speed",
    "NoClip",
    "Fly",
    "FlyUp",
    "FlyDown",
    "ExtInput",
    "HideFPS",
    "Screenshot",
    "Fullscreen",
    "ThirdPerson",
    "HideGUI",
    "AxisLines",
    "ZoomScrolling",
    "HalfSpeed",
    "DeleteBlock",
    "PickBlock",
    "PlaceBlock",
    "AutoRotate",
    "HotbarSwitching",
    "SmoothCamera",
    "DropBlock",
    "IDOverlay",
    "BreakableLiquids",
    "LookUp",
    "LookDown",
    "LookRight",
    "LookLeft",
    "Hotbar1",
    "Hotbar2",
    "Hotbar3",
    "Hotbar4",
    "Hotbar5",
    "Horbar6",
    "Hotbar7",
    "Hotbar8",
    "Hotbar9",
    "HotbarLeft",
    "HotbarRight",
];
