use crate::bindings::*;

pub const Key_Function_Names: &[&str] = &[
    "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12", "F13", "F14", "F15",
    "F16", "F17", "F18", "F19", "F20", "F21", "F22", "F23", "F24",
];

pub const Key_Ascii_Names: &[&str] = &[
    "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S",
    "T", "U", "V", "W", "X", "Y", "Z",
];

pub const Pad_Names: &[&str] = &[
    "PAD_A",
    "PAD_B",
    "PAD_X",
    "PAD_Y",
    "PAD_L",
    "PAD_R",
    "PAD_Z",
    "PAD_C",
    "PAD_D",
    "PAD_LEFT",
    "PAD_RIGHT",
    "PAD_UP",
    "PAD_DOWN",
    "PAD_START",
    "PAD_SELECT",
    "PAD_ZL",
    "PAD_ZR",
    "PAD_LSTICK",
    "PAD_RSTICK",
    "PAD_CLEFT",
    "PAD_CRIGHT",
    "PAD_CUP",
    "PAD_CDOWN",
];

pub const Pad_DisplayNames: &[&str] = &[
    "A", "B", "X", "Y", "L", "R", "Z", "C", "D", "LEFT", "RIGHT", "UP", "DOWN", "START", "SELECT",
    "ZL", "ZR", "LSTICK", "RSTICK", "CLEFT", "CRIGHT", "CUP", "CDOWN",
];

pub const Input_StorageNames: [&str; InputButtons_INPUT_COUNT as usize] = [
    "None",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "F13",
    "F14",
    "F15",
    "F16",
    "F17",
    "F18",
    "F19",
    "F20",
    "F21",
    "F22",
    "F23",
    "F24",
    "Tilde",
    "Minus",
    "Plus",
    "BracketLeft",
    "BracketRight",
    "Slash",
    "Semicolon",
    "Quote",
    "Comma",
    "Period",
    "BackSlash",
    "ShiftLeft",
    "ShiftRight",
    "ControlLeft",
    "ControlRight",
    "AltLeft",
    "AltRight",
    "WinLeft",
    "WinRight",
    "Up",
    "Down",
    "Left",
    "Right",
    "Number0",
    "Number1",
    "Number2",
    "Number3",
    "Number4",
    "Number5",
    "Number6",
    "Number7",
    "Number8",
    "Number9",
    "Insert",
    "Delete",
    "Home",
    "End",
    "PageUp",
    "PageDown",
    "Menu",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "Enter",
    "Escape",
    "Space",
    "BackSpace",
    "Tab",
    "CapsLock",
    "ScrollLock",
    "PrintScreen",
    "Pause",
    "NumLock",
    "Keypad0",
    "Keypad1",
    "Keypad2",
    "Keypad3",
    "Keypad4",
    "Keypad5",
    "Keypad6",
    "Keypad7",
    "Keypad8",
    "Keypad9",
    "KeypadDivide",
    "KeypadMultiply",
    "KeypadSubtract",
    "KeypadAdd",
    "KeypadDecimal",
    "KeypadEnter",
    "XButton1",
    "XButton2",
    "LeftMouse",
    "RightMouse",
    "MiddleMouse",
    "WheelUp",
    "WheelDown",
    "WheelLeft",
    "WheelRight",
    "XButton3",
    "XButton4",
    "XButton5",
    "XButton6",
    "VolumeMute",
    "VolumeUp",
    "VolumeDown",
    "Sleep",
    "MediaNext",
    "MediaPrev",
    "MediaPlay",
    "MediaStop",
    "BrowserPrev",
    "BrowserNext",
    "BrowserRefresh",
    "BrowserStop",
    "BrowserSsearch",
    "BrowserFavorites",
    "BrowserHome",
    "LaunchMail",
    "LaunchMedia",
    "LaunchApp1",
    "LaunchCalc",
    "PAD_A",
    "PAD_B",
    "PAD_X",
    "PAD_Y",
    "PAD_L",
    "PAD_R",
    "PAD_Z",
    "PAD_C",
    "PAD_D",
    "PAD_LEFT",
    "PAD_RIGHT",
    "PAD_UP",
    "PAD_DOWN",
    "PAD_START",
    "PAD_SELECT",
    "PAD_ZL",
    "PAD_ZR",
    "PAD_LSTICK",
    "PAD_RSTICK",
    "PAD_CLEFT",
    "PAD_CRIGHT",
    "PAD_CUP",
    "PAD_CDOWN",
];

pub const Input_DisplayNames: [&str; InputButtons_INPUT_COUNT as usize] = [
    "NONE",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "F13",
    "F14",
    "F15",
    "F16",
    "F17",
    "F18",
    "F19",
    "F20",
    "F21",
    "F22",
    "F23",
    "F24",
    "GRAVE",
    "MINUS",
    "PLUS",
    "LBRACKET",
    "RBRACKET",
    "SLASH",
    "SEMICOLON",
    "APOSTROPHE",
    "COMMA",
    "PERIOD",
    "BACKSLASH",
    "LSHIFT",
    "RSHIFT",
    "LCONTROL",
    "RCONTROL",
    "LALT",
    "RALT",
    "LWIN",
    "RWIN",
    "UP",
    "DOWN",
    "LEFT",
    "RIGHT",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "INSERT",
    "DELETE",
    "HOME",
    "END",
    "PRIOR",
    "DOWN",
    "MENU",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "RETURN",
    "ESCAPE",
    "SPACE",
    "BACK",
    "TAB",
    "CAPITAL",
    "SCROLL",
    "PRINT",
    "PAUSE",
    "NUMLOCK",
    "NUMPAD0",
    "NUMPAD1",
    "NUMPAD2",
    "NUMPAD3",
    "NUMPAD4",
    "NUMPAD5",
    "NUMPAD6",
    "NUMPAD7",
    "NUMPAD8",
    "NUMPAD9",
    "DIVIDE",
    "MULTIPLY",
    "SUBTRACT",
    "ADD",
    "DECIMAL",
    "NUMPADENTER",
    "XBUTTON1",
    "XBUTTON2",
    "LMOUSE",
    "RMOUSE",
    "MMOUSE",
    "WHEELUP",
    "WHEELDOWN",
    "WHEELLEFT",
    "WHEELRIGHT",
    "XBUTTON3",
    "XBUTTON4",
    "XBUTTON5",
    "XBUTTON6",
    "VOLUMEMUTE",
    "VOLUMEUP",
    "VOLUMEDOWN",
    "SLEEP",
    "MEDIANEXT",
    "MEDIAPREV",
    "MEDIAPLAY",
    "MEDIASTOP",
    "BROWSERPREV",
    "BROWSERNEXT",
    "BROWSERREFRESH",
    "BROWSERSTOP",
    "BROWSERSEARCH",
    "BROWSERFAVORITES",
    "BROWSERHOME",
    "LAUNCHMAIL",
    "LAUNCHMEDIA",
    "LAUNCHAPP1",
    "LAUNCHCALC",
    "A",
    "B",
    "X",
    "Y",
    "L",
    "R",
    "Z",
    "C",
    "D",
    "LEFT",
    "RIGHT",
    "UP",
    "DOWN",
    "START",
    "SELECT",
    "ZL",
    "ZR",
    "LSTICK",
    "RSTICK",
    "CLEFT",
    "CRIGHT",
    "CUP",
    "CDOWN",
];

pub const PadBind_Defaults: [BindMapping; InputBind__BIND_COUNT as usize] = [
    BindMapping {
        button1: InputButtons_CCPAD_UP as _,
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCPAD_DOWN as _,
        button2: 0,
    }, /* BIND_FORWARD, BIND_BACK */
    BindMapping {
        button1: InputButtons_CCPAD_LEFT as _,
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCPAD_RIGHT as _,
        button2: 0,
    }, /* BIND_LEFT, BIND_RIGHT */
    BindMapping {
        button1: InputButtons_CCPAD_1 as _,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_JUMP, BIND_RESPAWN */
    BindMapping {
        button1: InputButtons_CCPAD_START as _,
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCPAD_4 as _,
        button2: 0,
    }, /* BIND_SET_SPAWN, BIND_CHAT */
    BindMapping {
        button1: InputButtons_CCPAD_3 as _,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_INVENTORY, BIND_FOG */
    BindMapping {
        button1: InputButtons_CCPAD_START as _,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_SEND_CHAT, BIND_TABLIST */
    BindMapping {
        button1: InputButtons_CCPAD_2 as _,
        button2: InputButtons_CCPAD_L as _,
    },
    BindMapping {
        button1: InputButtons_CCPAD_2 as _,
        button2: InputButtons_CCPAD_3 as _,
    }, /* BIND_SPEED, BIND_NOCLIP */
    BindMapping {
        button1: InputButtons_CCPAD_2 as _,
        button2: InputButtons_CCPAD_R as _,
    }, /* BIND_FLY */
    BindMapping {
        button1: InputButtons_CCPAD_2 as _,
        button2: InputButtons_CCPAD_UP as _,
    },
    BindMapping {
        button1: InputButtons_CCPAD_2 as _,
        button2: InputButtons_CCPAD_DOWN as _,
    }, /* BIND_FLY_UP, BIND_FLY_DOWN */
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_EXT_INPUT, BIND_HIDE_FPS */
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_SCREENSHOT, BIND_FULLSCREEN, BIND_THIRD_PERSON, BIND_HIDE_GUI */
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_AXIS_LINES, BIND_ZOOM_SCROLL, BIND_HALF_SPEED */
    BindMapping {
        button1: InputButtons_CCPAD_L as _,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCPAD_R as _,
        button2: 0,
    }, /* BIND_DELETE_BLOCK, BIND_PICK_BLOCK, BIND_PLACE_BLOCK */
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_AUTOROTATE, BIND_HOTBAR_SWITCH, BIND_SMOOTH_CAMERA */
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_DROP_BLOCK, BIND_IDOVERLAY, BIND_BREAK_LIQUIDS */
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_LOOK_UP, BIND_LOOK_DOWN, BIND_LOOK_RIGHT, BIND_LOOK_LEFT */
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_HOTBAR_1, BIND_HOTBAR_2, BIND_HOTBAR_3 */
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_HOTBAR_4, BIND_HOTBAR_5, BIND_HOTBAR_6 */
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_HOTBAR_7, BIND_HOTBAR_8, BIND_HOTBAR_9 */
    BindMapping {
        button1: InputButtons_CCPAD_ZL as _,
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCPAD_ZR as _,
        button2: 0,
    }, /* BIND_HOTBAR_LEFT, BIND_HOTBAR_RIGHT */
];

pub const KeyBind_Defaults: [BindMapping; InputBind__BIND_COUNT as usize] = [
    BindMapping {
        button1: b'W',
        button2: 0,
    },
    BindMapping {
        button1: b'S',
        button2: 0,
    },
    BindMapping {
        button1: b'A',
        button2: 0,
    },
    BindMapping {
        button1: b'D',
        button2: 0,
    }, /* BIND_FORWARD - BIND_RIGHT */
    BindMapping {
        button1: InputButtons_CCKEY_SPACE as _,
        button2: 0,
    },
    BindMapping {
        button1: b'R',
        button2: 0,
    }, /* BIND_JUMP, BIND_RESPAWN */
    BindMapping {
        button1: InputButtons_CCKEY_ENTER as _,
        button2: 0,
    },
    BindMapping {
        button1: b'T',
        button2: 0,
    }, /* BIND_SET_SPAWN, BIND_CHAT */
    BindMapping {
        button1: b'B',
        button2: 0,
    },
    BindMapping {
        button1: b'F',
        button2: 0,
    }, /* BIND_INVENTORY, BIND_FOG */
    BindMapping {
        button1: InputButtons_CCKEY_ENTER as _,
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCKEY_TAB as _,
        button2: 0,
    }, /* BIND_SEND_CHAT, BIND_TABLIST */
    BindMapping {
        button1: InputButtons_CCKEY_LSHIFT as _,
        button2: 0,
    },
    BindMapping {
        button1: b'X',
        button2: 0,
    },
    BindMapping {
        button1: b'Z',
        button2: 0,
    }, /* BIND_SPEED, BIND_NOCLIP, BIND_FLY */
    BindMapping {
        button1: b'Q',
        button2: 0,
    },
    BindMapping {
        button1: b'E',
        button2: 0,
    }, /* BIND_FLY_UP, BIND_FLY_DOWN */
    BindMapping {
        button1: InputButtons_CCKEY_LALT as _,
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCKEY_F3 as _,
        button2: 0,
    }, /* BIND_EXT_INPUT, BIND_HIDE_FPS */
    BindMapping {
        button1: InputButtons_CCKEY_F12 as _,
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCKEY_F11 as _,
        button2: 0,
    }, /* BIND_SCREENSHOT, BIND_FULLSCREEN */
    BindMapping {
        button1: InputButtons_CCKEY_F5 as _,
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCKEY_F1 as _,
        button2: 0,
    }, /* BIND_THIRD_PERSON, BIND_HIDE_GUI */
    BindMapping {
        button1: InputButtons_CCKEY_F7 as _,
        button2: 0,
    },
    BindMapping {
        button1: b'C',
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCKEY_LCTRL as _,
        button2: 0,
    }, /* BIND_AXIS_LINES, BIND_ZOOM_SCROLL, BIND_HALF_SPEED */
    BindMapping {
        button1: InputButtons_CCMOUSE_L as _,
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCMOUSE_M as _,
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCMOUSE_R as _,
        button2: 0,
    }, /* BIND_DELETE_BLOCK, BIND_PICK_BLOCK, BIND_PLACE_BLOCK */
    BindMapping {
        button1: InputButtons_CCKEY_F6 as _,
        button2: 0,
    },
    BindMapping {
        button1: InputButtons_CCKEY_LALT as _,
        button2: 0,
    }, /* BIND_AUTOROTATE, BIND_HOTBAR_SWITCH */
    BindMapping {
        button1: InputButtons_CCKEY_F8 as _,
        button2: 0,
    },
    BindMapping {
        button1: b'G',
        button2: 0,
    }, /* BIND_SMOOTH_CAMERA, BIND_DROP_BLOCK */
    BindMapping {
        button1: InputButtons_CCKEY_F10 as _,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_IDOVERLAY, BIND_BREAK_LIQUIDS */
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_LOOK_UP, BIND_LOOK_DOWN, BIND_LOOK_RIGHT, BIND_LOOK_LEFT */
    BindMapping {
        button1: b'1',
        button2: 0,
    },
    BindMapping {
        button1: b'2',
        button2: 0,
    },
    BindMapping {
        button1: b'3',
        button2: 0,
    }, /* BIND_HOTBAR_1, BIND_HOTBAR_2, BIND_HOTBAR_3 */
    BindMapping {
        button1: b'4',
        button2: 0,
    },
    BindMapping {
        button1: b'5',
        button2: 0,
    },
    BindMapping {
        button1: b'6',
        button2: 0,
    }, /* BIND_HOTBAR_4, BIND_HOTBAR_5, BIND_HOTBAR_6 */
    BindMapping {
        button1: b'7',
        button2: 0,
    },
    BindMapping {
        button1: b'8',
        button2: 0,
    },
    BindMapping {
        button1: b'9',
        button2: 0,
    }, /* BIND_HOTBAR_7, BIND_HOTBAR_8, BIND_HOTBAR_9 */
    BindMapping {
        button1: 0,
        button2: 0,
    },
    BindMapping {
        button1: 0,
        button2: 0,
    }, /* BIND_HOTBAR_LEFT, BIND_HOTBAR_RIGHT */
];

pub const bindNames: [&str; InputBind__BIND_COUNT as usize] = [
    "Forward",
    "Back",
    "Left",
    "Right",
    "Jump",
    "Respawn",
    "SetSpawn",
    "Chat",
    "Inventory",
    "ToggleFog",
    "SendChat",
    "PlayerList",
    "Speed",
    "NoClip",
    "Fly",
    "FlyUp",
    "FlyDown",
    "ExtInput",
    "HideFPS",
    "Screenshot",
    "Fullscreen",
    "ThirdPerson",
    "HideGUI",
    "AxisLines",
    "ZoomScrolling",
    "HalfSpeed",
    "DeleteBlock",
    "PickBlock",
    "PlaceBlock",
    "AutoRotate",
    "HotbarSwitching",
    "SmoothCamera",
    "DropBlock",
    "IDOverlay",
    "BreakableLiquids",
    "LookUp",
    "LookDown",
    "LookRight",
    "LookLeft",
    "Hotbar1",
    "Hotbar2",
    "Hotbar3",
    "Hotbar4",
    "Hotbar5",
    "Horbar6",
    "Hotbar7",
    "Hotbar8",
    "Hotbar9",
    "HotbarLeft",
    "HotbarRight",
];
