name: Build

on:
  pull_request:
    branches: [master, main]
  push:
    branches: ["*"]
    tags: ["*"]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  linux-nix:
    uses: SpiralP/github-reusable-workflows/.github/workflows/build.yml@c486e35ce06f991c4565d2d8064948aa5b520047 # main

  windows-x86_64:
    runs-on: windows-2025
    permissions:
      contents: write # for publishing docs
    steps:
      - uses: SpiralP/rust-classicube-sys/.github/actions/install-build-test@main
        with:
          target: x86_64-pc-windows-msvc

      - uses: ./.github/actions/deploy-docs
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          target: x86_64-pc-windows-msvc

  windows-i686:
    runs-on: windows-2025
    steps:
      - uses: SpiralP/rust-classicube-sys/.github/actions/install-build-test@main
        with:
          target: i686-pc-windows-msvc

  linux-x86_64:
    runs-on: ubuntu-24.04
    steps:
      - uses: SpiralP/rust-classicube-sys/.github/actions/install-build-test@main
        with:
          target: x86_64-unknown-linux-gnu

  linux-i686:
    runs-on: ubuntu-24.04
    steps:
      - name: Install deps
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc-multilib g++-multilib

      - uses: SpiralP/rust-classicube-sys/.github/actions/install-build-test@main
        with:
          target: i686-unknown-linux-gnu

  mac-x86_64:
    runs-on: macos-14
    steps:
      - uses: SpiralP/rust-classicube-sys/.github/actions/install-build-test@main
        with:
          target: x86_64-apple-darwin

  mac-aarch64:
    runs-on: macos-14
    steps:
      - uses: SpiralP/rust-classicube-sys/.github/actions/install-build-test@main
        with:
          target: aarch64-apple-darwin
