name: release

on:
  push:
    branches: [main, master, alpha, beta]
  workflow_dispatch:

permissions: {} # each job declares its own

jobs:
  build:
    uses: ./.github/workflows/build.yml
    if: "${{ ! startsWith(github.event.head_commit.message, 'chore(release): ') }}"
    permissions:
      contents: read # for checkout in called workflow

  deploy-docs:
    name: Deploy docs to Pages
    runs-on: ubuntu-24.04
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0

  get-version-metadata:
    runs-on: ubuntu-24.04
    needs: build
    if: "${{ ! startsWith(github.event.head_commit.message, 'chore(release): ') }}"
    permissions:
      contents: read
    outputs:
      version-metadata: ${{ steps.get-version-metadata.outputs.version-metadata }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive
      - id: get-version-metadata
        run: |
          classicube_version="$(git -C ./ClassiCube/ describe --exact-match --tags HEAD)"
          test -z "$classicube_version" && echo "classicube_version is empty" && exit 1
          version_metadata="ClassiCube $classicube_version"
          echo "version-metadata=$version_metadata" | tee -a "$GITHUB_OUTPUT"

  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@a7630d0468733e888f9104a242063f1bcb6a0022 # main
    needs: get-version-metadata
    if: "${{ needs.get-version-metadata.outputs.version-metadata }}"
    permissions: {} # none, since we use a custom app
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: false # do not cancel in-progress jobs
    with:
      cargo-publish: true
      environment-name: release
      replace-files: |
        Cargo.lock
        Cargo.toml
      package-name: classicube-sys
      version-metadata: ${{ needs.get-version-metadata.outputs.version-metadata }}
    secrets:
      app-client-id: ${{ secrets.APP_CLIENT_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
