name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Install deps
      run: sudo apt-get -y install mesa-common-dev libopenal-dev libcurl4-openssl-dev
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Generate docs
      run: cargo doc
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./target/doc
